### ISSUE TITLE
java.lang.IllegalStateException: Response is closed after browser refresh.

### ISSUE THREAD

**Issue by moxit0** [aesteve/vertx-sse#13]
Hi,
first I have to say my admiration for the work you have done. I am using your Vertx SSE implementation to show notification coming from MQTT topic  on the client (Angular 5). In general following you examples I set up a SSEHandler and everything works except in case of  browser refresh. If you refresh the browser while client and server are connected exception on the server side is thrown: 
`
SEVERE: Unhandled exception
java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:547)
	at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:573)
	at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:296)
	at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:52)
	at io.vertx.ext.web.handler.sse.impl.SSEConnectionImpl.writeHeader(SSEConnectionImpl.java:143)
	at io.vertx.ext.web.handler.sse.impl.SSEConnectionImpl.withHeader(SSEConnectionImpl.java:131)
	at io.vertx.ext.web.handler.sse.impl.SSEConnectionImpl.retry(SSEConnectionImpl.java:71)
	at io.vertx.ext.web.handler.sse.impl.SSEHandlerImpl.lambda$handle$0(SSEHandlerImpl.java:37)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

then new data is no able to be delivered to the client throw SSE. Have you run into such issue and do you have any clue for a workaround.

**Comment by aesteve** [comment]
Can you try with the last version of the codebase ? 

I think I fixed it because I faced it, too.
